version: '3'
services:
  dbpostgres:
    image: postgres
    volumes:
    - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
    - "50432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: simplexchat