spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simplexchat
    username: pguser
    password: pguser
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
  thymeleaf:
    cache: false

changelog:
  path: /changelog/changelog.xml